services:
  - docker

before_install:
  - ls -la
  - sudo apt-get update
  - sudo apt-get install g++ build-essential
  
script:
  - whoami
  - chmod +x ./scripts/docker_build.sh
  - ./scripts/docker_build.sh
  
