#!/usr/bin/env bash

shellcheck_version="0.6.0"
shellcheck_hash="f5c88adbeb616765fa7247f17bdfdb932544b22bd6daf4fff4c6b074601e97d9083d514ecf73027dd3422d7782abcd79206023fc32392fd3fdb127be4d43d66b"

set -e -u -x
source ./tasks/helpers.sh

task_working_dir
download "https://storage.googleapis.com/shellcheck/shellcheck-v$shellcheck_version.linux.x86_64.tar.xz" "sha512" "$shellcheck_hash"
extract_download "shellcheck-v$shellcheck_version.linux.x86_64.tar.xz"

install -D -m 755 "shellcheck-v$shellcheck_version/shellcheck" "$TEST_INSTALL_PREFIX/bin/shellcheck"

stamp
